spring:
  application:
    name: library
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

mvc:
  hiddenmethod:
    filter:
      enabled: true

server:
  servlet:
    context-path: '/api/library'

# MyBatis-Plus 相關配置
mybatis-plus:
  global-config:
    # 關閉附帶的橫幅廣告的設定
    banner: false
    db-config:
      # 主鍵生成策略為自動增長
      id-type: auto
      # 開啟資料庫資料表名稱的底線命名規則
      table-underline: true
  # 指定 Mapper XML 檔案的路徑，專案生成的 XML 檔案全部放在 resource 目錄下的 mapper 檔案中
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    # 日誌輸出到主控台，資料庫查詢、刪除等執行日誌都會輸出到主控台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
