spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/library_v1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Taipei&rewriteBatchedStatements=true
    username: root
    password: guang000

    druid:
      initial-size: 5
      min-idle: 15
      max-active: 30
      remove-abandoned-timeout: 180
      max-wait: 300000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000

      filters: stat,wall,log4j2

      stat-view-servlet:
        enabled: true
        loginUsername: root
        loginPassword: guang000
        allow:

      web-stat-filter:
        enabled: true
        session-stat-enable: true
        session-stat-max-count: 1000
        url-pattern: /*

      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000



